# Site settings
title: Hi, I'm Koray.
description: Koray Yenal's professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://korayyenal.github.io

# User settings
username: Koray Yenal
user_title:
user_job_title: Ex-Google, Data Science MSc student
email: koray.yenal [at] hec.ca
twitter_username: korayyenal
github_username:  korayyenal

exclude: ['package.json', 'src' , 'node_modules']
